### ISSUE TITLE
Autocompletion with Init-Signatures of C extension classes

### ISSUE THREAD

**Issue by MSeifert04** [ipython/ipython#10044]
I don't quite get the autocompletion to work with C extension classes. These classes have a Signature (at least since python 3.4 by utilizing `__text_signature__`) but it seems IPython cannot autocomplete the parameters in `__text_signature__`.

For example:

```
>>> import pickle
>>> import inspect
>>> inspect.Signature.from_callable(pickle.Pickler)
<Signature (file, protocol=None, fix_imports=True)>
```

Note that the signature is saved as `__text_signature__`-attribute on ``pickle.Pickle``.

I would expect that after printing`pickle.Pickler(` and then hitting TAB it would show:
```
file=
protocol=
fix_imports=
# other stuff
```
but it doesn't. 

Classes seem to be special in this regard - IPython is definitly able to get the parameters for functions and methods! It just doesn't work for classes.

**Comment by ivanov** [comment]
Thank you for your report. I have a patch I'll try to put up later on today that should solve this issue.

**Comment by MSeifert04** [comment]
@ivanov I don't know if the report was misleading, so just to clarify: The problem I'm experiencing is with parameter tab completion for classes without `__init__` but with `__text_signature__`, not with class-attribute tab completion.

I just tried installing your patch and it seems it still cannot find the `Pickler.__init__` attributes, like `file`, `protocol` or `fix_imports`.

**Comment by MSeifert04** [comment]
@Carreau I tried it with the latest development version but I can still reproduce the issue.

**Comment by Carreau** [comment]
Sorry github was over-eager in analyzing the text in #10046 reopening.

**Comment by MSeifert04** [comment]
Thank you 👍
