### ISSUE TITLE
ipython 6.2.1 does not work on OS Windows: No Windows console found. Are you running cmd.exe?

### ISSUE THREAD

**Issue by bialix** [ipython/ipython#10910]
Python 3.3 64 bit on Windows 7

prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

Below the full log of my actions in separate empty directory and empty virtual env:

```
C:\Temp\test>dir /b

C:\Temp\test>python -V
Python 3.3.5

C:\Temp\test>python -m virtualenv .
Using base prefix 'D:\\Python\\3.3-64'
New python executable in C:\Temp\test\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\Temp\test>dir /b
Include
Lib
pip-selfcheck.json
Scripts

C:\Temp\test>cd Scripts

C:\Temp\test\Scripts>pip install ipython
Collecting ipython
  Using cached ipython-6.2.1-py3-none-any.whl
Collecting win-unicode-console>=0.5; sys_platform == "win32" and python_version < "3.6" (from ipython)
Collecting pathlib2; python_version == "3.3" (from ipython)
  Using cached pathlib2-2.3.0-py2.py3-none-any.whl
Collecting decorator (from ipython)
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting jedi>=0.10 (from ipython)
  Using cached jedi-0.11.0-py2.py3-none-any.whl
Collecting pickleshare (from ipython)
  Using cached pickleshare-0.7.4-py2.py3-none-any.whl
Collecting traitlets>=4.2 (from ipython)
  Using cached traitlets-4.3.2-py2.py3-none-any.whl
Collecting typing; python_version <= "3.4" (from ipython)
  Using cached typing-3.6.2-py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython)
  Using cached prompt_toolkit-1.0.15-py3-none-any.whl
Collecting pygments (from ipython)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting colorama; sys_platform == "win32" (from ipython)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython)
Requirement already satisfied: setuptools>=18.5 in c:\temp\test\lib\site-packages (from ipython)
Collecting six (from pathlib2; python_version == "3.3"->ipython)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "3.3"->ipython)
  Using cached scandir-1.6-cp33-cp33m-win_amd64.whl
Collecting parso==0.1.0 (from jedi>=0.10->ipython)
  Using cached parso-0.1.0-py2.py3-none-any.whl
Collecting ipython-genutils (from traitlets>=4.2->ipython)
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting enum34; python_version == "3.3" (from traitlets>=4.2->ipython)
  Using cached enum34-1.1.6-py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython)
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Installing collected packages: win-unicode-console, six, scandir, pathlib2, decorator, parso, jedi, pickleshare, ipython-genutils, enum34, traitlets, typing, wcwidth, prompt-toolkit, pygments, coloram
a, simplegeneric, ipython
Successfully installed colorama-0.3.9 decorator-4.1.2 enum34-1.1.6 ipython-6.2.1 ipython-genutils-0.2.0 jedi-0.11.0 parso-0.1.0 pathlib2-2.3.0 pickleshare-0.7.4 prompt-toolkit-1.0.15 pygments-2.2.0 sc
andir-1.6 simplegeneric-0.8.1 six-1.11.0 traitlets-4.3.2 typing-3.6.2 wcwidth-0.1.7 win-unicode-console-0.5

C:\Temp\test\Scripts>dir /b
activate
activate.bat
activate.ps1
activate_this.py
deactivate.bat
easy_install-3.3.exe
easy_install.exe
iptest.exe
iptest3.exe
ipython.exe
ipython3.exe
pip.exe
pip3.3.exe
pip3.exe
pygmentize.exe
python.exe
pythonw.exe
wheel.exe

C:\Temp\test\Scripts>ipython
Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

Traceback (most recent call last):
  File "c:\temp\test\lib\site-packages\prompt_toolkit\interface.py", line 413, in run
    self._redraw()
  File "c:\temp\test\lib\site-packages\prompt_toolkit\interface.py", line 358, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "c:\temp\test\lib\site-packages\prompt_toolkit\renderer.py", line 450, in render
    previous_width=(self._last_size.columns if self._last_size else 0))
  File "c:\temp\test\lib\site-packages\prompt_toolkit\renderer.py", line 128, in _output_screen_diff
    output.erase_down()
  File "c:\temp\test\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 199, in erase_down
    self._erase(start, length)
  File "c:\temp\test\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 218, in _erase
    sbinfo = self.get_win32_screen_buffer_info()
  File "c:\temp\test\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 172, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\3.3-64\Lib\runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Python\3.3-64\Lib\runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "C:\Temp\test\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\temp\test\lib\site-packages\IPython\__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\temp\test\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\temp\test\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "c:\temp\test\lib\site-packages\IPython\terminal\interactiveshell.py", line 480, in mainloop
    self.interact()
  File "c:\temp\test\lib\site-packages\IPython\terminal\interactiveshell.py", line 463, in interact
    code = self.prompt_for_code()
  File "c:\temp\test\lib\site-packages\IPython\terminal\interactiveshell.py", line 376, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "c:\temp\test\lib\site-packages\prompt_toolkit\interface.py", line 425, in run
    self._redraw()
  File "c:\temp\test\lib\site-packages\prompt_toolkit\interface.py", line 358, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "c:\temp\test\lib\site-packages\prompt_toolkit\renderer.py", line 450, in render
    previous_width=(self._last_size.columns if self._last_size else 0))
  File "c:\temp\test\lib\site-packages\prompt_toolkit\renderer.py", line 128, in _output_screen_diff
    output.erase_down()
  File "c:\temp\test\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 199, in erase_down
    self._erase(start, length)
  File "c:\temp\test\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 218, in _erase
    sbinfo = self.get_win32_screen_buffer_info()
  File "c:\temp\test\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 172, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by bialix** [comment]
Of course I'm running cmd.exe - is it illegal now?

**Comment by bialix** [comment]
The same with version 5.0. I've read news and found you've switched to use prompt_toolkit. And that library seems does not work on Windows.

**Comment by bialix** [comment]
OK, ipython 4.2 with pyreadline still works. I should remember to install exactly that version.
"Thank" you.

**Comment by takluyver** [comment]
There's nothing wrong with using `cmd.exe`, and prompt_toolkit is meant to work on Windows. There's some mysterious bug that crops up occasionally that results in that error. At least one cause of it has been fixed, but apparently there's another.

cc @jonathanslenders - how do we debug the dreaded `NoConsoleScreenBufferError` ?

**Comment by bialix** [comment]
I've just tested on almost fresh installation of Python 3.4 64-bit with virtualenv. And it worked.
Maybe it's somehow related to Python 3.3 or maybe virtualenv not fully isolate ipython from installed packages.

**Comment by jonathanslenders** [comment]
The code for testing would be the following:

```python
import sys
from prompt_toolkit.terminal.win32_output import Win32Output
output = Win32Output(sys.stdout)
sbinfo = output.get_win32_screen_buffer_info()
print(sbinfo)  # This should print the console screen buffer info or raise a `NoConsoleScreenBufferError`
```

Honestly, I'm still not sure why in certain situations it doesn't work. There are differences between Python versions and Windows versions. If it breaks, then it's because the API call to the Win32 kernel fails. There was also a *very* weird issue where calling this function through another function that wrapped it failed systematically on some systems. See this comment: https://github.com/jonathanslenders/python-prompt-toolkit/blob/4476b3c28add85c5a8169fbb81ded8c3b845e588/prompt_toolkit/terminal/win32_output.py#L144

Maybe it's indeed related to Python 3.3

**Comment by bialix** [comment]
@jonathanslenders I've just checked your code example and it works:

C:\Temp\test\venv\Scripts>python.EXE
Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> from prompt_toolkit.terminal.win32_output import Win32Output
>>> output = Win32Output(sys.stdout)
>>> sbinfo = output.get_win32_screen_buffer_info()
>>> print(sbinfo)
(52,200,51,0,7,0,0,51,199,52,200)

But ipython still raises NoConsoleScreenBufferError

**Comment by jonathanslenders** [comment]
Very weird.
I wonder whether at some point the window handle ( ``Win32Output.hconsole``) becomes corrupt.

What if you would change ``get_win32_screen_buffer_info`` [1], so that if it is not successful, instead of raising an error, it does the following:
```python
if success:
    return sbinfo
else:
    # raise NoConsoleScreenBufferError
    self.hconsole = windll.kernel32.GetStdHandle(STD_OUTPUT_HANDLE)
    return self.get_win32_screen_buffer_info()  # Call itself again.
```

[1] https://github.com/jonathanslenders/python-prompt-toolkit/blob/4476b3c28add85c5a8169fbb81ded8c3b845e588/prompt_toolkit/terminal/win32_output.py#L140

**Comment by bialix** [comment]
I wonder if there are second thread involved in this bug, or ipython is always single-threaded?

**Comment by bialix** [comment]
> Very weird.
> I wonder whether at some point the window handle ( Win32Output.hconsole) becomes corrupt.

Yep, it seems your assumption are not far from true.
I've added logging to win32_output.py and found that self.hconsole is 19 in constructor and then later in get_win32_screen_buffer_info. But error was still here with ipython.

But when I changed the code as following:

```
    def get_win32_screen_buffer_info(self):
        self.flush()
        sbinfo = CONSOLE_SCREEN_BUFFER_INFO()
        hconsole = windll.kernel32.GetStdHandle(STD_OUTPUT_HANDLE)
        success = windll.kernel32.GetConsoleScreenBufferInfo(hconsole, byref(sbinfo))
```

And it started to work fine and ipython now works. Quite strange.

**Comment by jonathanslenders** [comment]
Hi @bialix,

Thanks a lot for testing! This is really helpful. I'm willing to merge this as a fix if it doesn't break anything. I'll check whether I can reproduce it on a Win 7 Python 3.3 64bit machine. Feel free to open a pull request.

Some related issues: https://github.com/jonathanslenders/python-prompt-toolkit/issues/406 and https://github.com/jonathanslenders/python-prompt-toolkit/issues/86

**Comment by bialix** [comment]
@jonathanslenders I did more research. According to MSDN if GetConsoleScreenBufferInfo is failed then detailed info should be obtained with GetLastError. I've added call to GetLastError and indeed: last error code is 6 which is

> ERROR_INVALID_HANDLE
> 6 (0x6)
> The handle is invalid.

 https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms681382(v=vs.85).aspx

Maybe it's worth to check GetLastError and refresh self.hconsole handle it this case?

**Comment by bialix** [comment]
@jonathanslenders May I suggest the following changes:

```
    def get_win32_screen_buffer_info(self, again=False):
        self.flush()
        sbinfo = CONSOLE_SCREEN_BUFFER_INFO()
        success = windll.kernel32.GetConsoleScreenBufferInfo(self.hconsole, byref(sbinfo))
        if success:
            return sbinfo
        else:
            err = windll.kernel32.GetLastError()
            logging.debug("Win32Output.get_win32_screen_buffer_info: last err=%s", repr(err))
            if not again:
                if err == 6:    # ERROR_INVALID_HANDLE
                    self.hconsole = self.get_stdout_handle() #windll.kernel32.GetStdHandle(STD_OUTPUT_HANDLE)
                    return self.get_win32_screen_buffer_info(True)
            raise NoConsoleScreenBufferError

    def get_stdout_handle(self):
        handle = windll.kernel32.GetStdHandle(STD_OUTPUT_HANDLE)
        if handle == -1:    # INVALID_HANDLE_VALUE
            raise InvalidHandleValue
        return handle
```

**Comment by bialix** [comment]
I suspect some race condition here. Ater I've implemented the changes above (additional method get_stdout_handle) then I no more get error with handle. That might explain why this issue is so elusive.

**Comment by jonathanslenders** [comment]
Interesting about ``GetLastError`` is that it already returns 6 in an empty Python shell. I'm not sure what that means.

![image](https://user-images.githubusercontent.com/216638/33150407-97577b90-cfd3-11e7-8751-ff674fa41927.png)

The code looks good to me. We still don't know the actual underlying cause, but I'm happy enough to merge this, given the trouble that it saves in certain situations.

**Comment by bialix** [comment]
`
Probably Python has tried to make some Windows API calls behind the scenes? Anyway, I can't confirm:

```
Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> print(ctypes.windll.kernel32.GetLastError())
0
```

I suspect it depends on Python version, build and underlying system.
