### ISSUE TITLE
F2 opens a different editor than %edit

### ISSUE THREAD

**Issue by switowski** [ipython/ipython#11682]
I recently found about the F2 shortcut (convenient!) to open the editor (as introduced in https://github.com/ipython/ipython/pull/9929). But I was surprised that the `%edit` command opens vim, while the F2 key opens nano (with `$EDITOR` variable being unset). I can see that this inconsistence is cause by the fact that `%edit` has 'vi' set as a default editor on Linux, while F2 is delegating the editor opening to prompt_toolkit that checks a bunch of editors (https://github.com/prompt-toolkit/python-prompt-toolkit/blob/aa44ef7b0f097d4517f8a23cc599d7d338533a48/prompt_toolkit/buffer.py#L1404).
Do you think it makes sense to clarify this in the documentation somewhere (at least the F2 feature as it's pretty cool)? I can submit a PR that mentions the F2 key in the %edit magic method documentation (unless there is a better place to put it?) and why a different editor might be used.

**Comment by npcole** [comment]
F2 should surely follow the logic of %edit -- and check $EDITOR as a standard, at least.

**Comment by acegallagher** [comment]
Hmmmm. How funny, I can't be the only person this drives crazy? I would have imagined that the majority of ipython users use F2 to make larger modifications to the codeblocks. The buffer.py file referenced by @switowski here checks for $EDITOR but then doesn't use it at the moment, it has to be a minor change to get it to actually use that if set? Also, I'm not an ipython contributor, but shouldn't it just call the same code as %edit under the hood? 

I'd be happy to make the change and submit a pull request...

**Comment by MrMino** [comment]
Pretty sure this has been fixed: on 8.1, running IPython after `export EDITOR=nano` shows nano on both `%edit` and <kbd>F2</kbd>, `export EDITOR=vim` makes it use vim, etc.

If someone else is still running into this issue, please ping us here - we'll reopen.

**Comment by acegallagher** [comment]
Hey there. I still have this issue and recently revisited it today. Would be great if I could help figure out why. I'm running ipython 8.4

**Comment by MrMino** [comment]
@acegallagher C-x C-e is a Bash binding, no?

Could you post the output of `env`?

**Comment by acegallagher** [comment]
@MrMino 

Thank you for the effort in responding. It seems I've filed a not-your-bug bug. It's in fact my error. I'm opening ipython in fish shell and in my fish config I *had* `set EDITOR 'emacsclient -t -nw`... 

Which it turns out doesn't actually export the variables, as very clearly outlined in the fish shell documentation. However, I didn't notice because, even though EDITOR isn't actually exported and therefore inherited by ipython, it *does* appear in the output of env. For reasons I don't really comprehend.

FYI. C-x C-e is snagged by ipython when you have the emacs bindings set. 

I think you can re-close this.
