### ISSUE TITLE
Autoreload super slow when large lists are present in memory

### ISSUE THREAD

**Issue by ashaffer** [ipython/ipython#12269]
Recently it seems some code was added to update object instances in this issue [11588](https://github.com/ipython/ipython/issues/11588). This is great that that's working, but now when I have a long list of dictionaries in memory, my reloads take *forever*.

Is there a way maybe to notify autoreload that a particular list doesn't need to be checked? It's simple to reproduce:

```x = [{'a': i} for i in range(50000000)]```

Just stick this in a cell, run it, and then trigger a reload. It should be quite slow.

**Comment by daharn** [comment]
Just to verify: Has this been resolved by https://github.com/ipython/ipython/pull/11876?

**Comment by vctoir** [comment]
The issues seems to be still present in

jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : 5.0.2
ipython          : 7.20.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 3.0.7
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5

**Comment by daharn** [comment]
Can you provide a full example? I couldn't reproduce any odd behavior following @ashaffer's instructions.
