### ISSUE TITLE
Crash while rendering traceback

### ISSUE THREAD

**Issue by eric-wieser** [ipython/ipython#12467]
On a clean checkout of 58006f3

```
PS C:\Users\wiese\Repos\lean\mathlib> py -3.8 -m IPython
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.0.dev -- An enhanced Interactive Python. Type '?' for help.

In [1]: from enum import Enum

In [2]: class MyEnum(Enum):
   ...:     X = 1
   ...:

In [3]: MyEnum(2)
ValueError: 2 is not a valid MyEnum

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 3410, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-a0dabac034d8>", line 1, in <module>
    MyEnum(2)
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\enum.py", line 595, in __new__
    raise exc
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 2 is not a valid MyEnum

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 2042, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 3330, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 3427, in run_code
    self.showtraceback(running_compiled_code=True)
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 1002, in structured_traceback
    return FormattedTB.structured_traceback(
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 902, in structured_traceback
    return VerboseTB.structured_traceback(
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 777, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 703, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 753, in get_records
    return list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\stack_data\core.py", line 527, in stack_data
    if is_frame(frame_or_tb):
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\stack_data\utils.py", line 87, in is_frame
    assert_(isinstance(frame_or_tb, (types.FrameType, types.TracebackType)))
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\stack_data\utils.py", line 168, in assert_
    raise error
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 2042, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 2916, in _run_cell
    return runner(coro)
  File "c:\users\wiese\repos\forks\ipython\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 3138, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 3349, in run_ast_nodes
    self.showtraceback()
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 1002, in structured_traceback
    return FormattedTB.structured_traceback(
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 902, in structured_traceback
    return VerboseTB.structured_traceback(
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 777, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 703, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 753, in get_records
    return list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\stack_data\core.py", line 527, in stack_data
    if is_frame(frame_or_tb):
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\stack_data\utils.py", line 87, in is_frame
    assert_(isinstance(frame_or_tb, (types.FrameType, types.TracebackType)))
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\stack_data\utils.py", line 168, in assert_
    raise error
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 2042, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\wiese\repos\forks\ipython\IPython\__main__.py", line 14, in <module>
    start_ipython()
  File "c:\users\wiese\repos\forks\ipython\IPython\__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "c:\users\wiese\repos\forks\ipython\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "c:\users\wiese\repos\forks\ipython\IPython\terminal\interactiveshell.py", line 564, in mainloop
    self.interact()
  File "c:\users\wiese\repos\forks\ipython\IPython\terminal\interactiveshell.py", line 555, in interact
    self.run_cell(code, store_history=True)
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 2870, in run_cell
    result = self._run_cell(
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 2921, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "c:\users\wiese\repos\forks\ipython\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 1002, in structured_traceback
    return FormattedTB.structured_traceback(
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 902, in structured_traceback
    return VerboseTB.structured_traceback(
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 777, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 703, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "c:\users\wiese\repos\forks\ipython\IPython\core\ultratb.py", line 753, in get_records
    return list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\stack_data\core.py", line 527, in stack_data
    if is_frame(frame_or_tb):
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\stack_data\utils.py", line 87, in is_frame
    assert_(isinstance(frame_or_tb, (types.FrameType, types.TracebackType)))
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\stack_data\utils.py", line 168, in assert_
    raise error
AssertionError

If you suspect this is an IPython 8.0.0.dev bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by eric-wieser** [comment]
What's happening is that `etb` is `None` on this line:

https://github.com/ipython/ipython/blob/58006f3d544616bbd51e2e208b8220899d63eb31/IPython/core/ultratb.py#L753

Which causes as `AssertionError`, and then things get wacky

**Comment by eric-wieser** [comment]
Here's a much simpler reproduction:
```
In [13]: v = ValueError()

In [14]: v.__context__ = ValueError()

In [15]: raise v
```

**Comment by eric-wieser** [comment]
Which is what `enum.Enum` is doing here:

https://github.com/python/cpython/blob/a74eea238f5baba15797e2e8b570d153bc8690a7/Lib/enum.py#L585-L594

@ethanfurman, these repeated tracebacks strike me like a bug in `enum`:
```python
>>> from enum import Enum
>>> class MyEnum(Enum):
...     X = 1
...
>>> MyEnum(2)
ValueError: 2 is not a valid MyEnum

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\enum.py", line 595, in __new__
    raise exc
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 2 is not a valid MyEnum
```

**Comment by aulemahal** [comment]
I think I can reproduce a similar problem with another case:

```python3
raise ValueError('one') from ValueError('two')
```

I guess this is related to the example in an above comment.

Happens in IPython 8.0.1, with Python 3.9.6.

Full traceback:

<details>

```python3
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %config Application.verbose_crash=True

In [2]: raise ValueError("what") from ValueError("wack")
Error in sys.excepthook:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/pathlib.py", line 1429, in is_dir
    return S_ISDIR(self.stat().st_mode)
AttributeError: 'str' object has no attribute 'stat'

Original exception was:
ValueError: wack

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-69a344230c6c>", line 1, in <module>
ValueError: what

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/xclim-pip/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 316, in start
    self.shell.mainloop()
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 611, in mainloop
    self.interact()
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 604, in interact
    self.run_cell(code, store_history=True)
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/opt/miniconda3/envs/xclim-pip/lib/python3.9/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError
```

</details>

**Comment by lesteve** [comment]
Let me try to summarise my understanding of the issue (while at the same trying not to sound too demanding):

- this is a regression in IPython 8
- it seems like this affects many people. Running code that uses `raise from` inside Jupyter interfaces or IPython will trigger the bug. The behaviour is the following:
    + JupyterLab or classic notebook cell seems to hangs (i.e. you see the `*` in the prompt) as in https://github.com/joblib/joblib/issues/1252#issue-1117440690
    + IPython crashes (you get back to the terminal where you ran the `ipython` command)

**Comment by lesteve** [comment]
FWIW a `git bisect` points to #11886

**Comment by jstucke** [comment]
I don't know if this helps with debugging but this also happens with exceptions in `multiprocessing.pool.Pool`:

```python
from multiprocessing.pool import Pool

def foo(x):
    raise Exception()

Pool(1).map(foo, [1])
```

Tested in latest Python 3.10 docker container with IPython 8.0.1:

<details>

```python
root@0d7056b87b09:/# ipython
Python 3.10.2 (main, Feb  8 2022, 04:44:29) [GCC 10.2.1 20210110]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from multiprocessing.pool import Pool

In [2]: def foo(x):
   ...:     raise Exception()

In [3]: Pool(1).map(foo, [1])
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "<ipython-input-2-f1f53f013b9a>", line 2, in foo
    raise Exception()
Exception
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-6128068d2903>", line 1, in <module>
    Pool(1).map(foo, [1])
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'Exception' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.10/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/usr/local/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 316, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 611, in mainloop
    self.interact()
  File "/usr/local/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 604, in interact
    self.run_cell(code, store_history=True)
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/usr/local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

If you suspect this is an IPython 8.0.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

root@0d7056b87b09:/# 
```

</details>

**Comment by jstucke** [comment]
I did some digging in the code and the reason for the crash seems to lie in `IPython.core.ultratb.VerboseTB.format_exception_as_a_whole`. This method will be called from the `while` loop in `structured_traceback` for each exception in the list of chained exceptions. The problem comes with the last exception in the chain where `etb` can be `None` in some corner cases (e.g. with the `Pool` above). This triggers the newly introduced `assert etb is not None` (which was not present in IPython 7.x though `etb` was also `None` here in some cases). An easy fix would be to check if `etb` is `None` in the while loop but this would also hide the last chained exception in the traceback, so it should probably be handled in `format_exception_as_a_whole`

**Comment by lesteve** [comment]
I think this issue can be closed, since it has been fixed in 8.2 by #13588.

At least the two snippets https://github.com/ipython/ipython/issues/12467#issuecomment-1031525779 and https://github.com/ipython/ipython/issues/12467#issuecomment-1040348356 now raise an exception rather than crashing IPython.

Thanks a lot for the fix!

**Comment by aulemahal** [comment]
I confirm that my issue with `raise ValueError() from ValueError()` has been fixed as well in 8.2.

**Comment by The-Compiler** [comment]
I can still reproduce this with IPython 8.6.0 (in JupyterLab 3.5.0) using:

```python
import argparse
parser = argparse.ArgumentParser()
group = parser.add_mutually_exclusive_group()
group.add_argument("-a")
group.add_argument("-b")
parser.parse_args(["-a", "-b"])
```

This results in:

```pytb
usage: ipykernel_launcher.py [-h] [-a A | -b B]
ipykernel_launcher.py: error: argument -a: expected one argument
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
File /opt/conda/lib/python3.10/argparse.py:1859, in ArgumentParser.parse_known_args(self, args, namespace)
   1858 try:
-> 1859     namespace, args = self._parse_known_args(args, namespace)
   1860 except ArgumentError:

File /opt/conda/lib/python3.10/argparse.py:2068, in ArgumentParser._parse_known_args(self, arg_strings, namespace)
   2067     # consume the next optional and any arguments for it
-> 2068     start_index = consume_optional(start_index)
   2070 # consume any positionals following the last Optional

File /opt/conda/lib/python3.10/argparse.py:1998, in ArgumentParser._parse_known_args.<locals>.consume_optional(start_index)
   1997 selected_patterns = arg_strings_pattern[start:]
-> 1998 arg_count = match_argument(action, selected_patterns)
   1999 stop = start + arg_count

File /opt/conda/lib/python3.10/argparse.py:2163, in ArgumentParser._match_argument(self, action, arg_strings_pattern)
   2160         msg = ngettext('expected %s argument',
   2161                        'expected %s arguments',
   2162                        action.nargs) % action.nargs
-> 2163     raise ArgumentError(action, msg)
   2165 # return the number of arguments matched

ArgumentError: argument -a: expected one argument

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In [14], line 6
      5 group.add_argument("-b")
----> 6 parser.parse_args(["-a", "-b"])

File /opt/conda/lib/python3.10/argparse.py:1826, in ArgumentParser.parse_args(self, args, namespace)
   1825 def parse_args(self, args=None, namespace=None):
-> 1826     args, argv = self.parse_known_args(args, namespace)
   1827     if argv:

File /opt/conda/lib/python3.10/argparse.py:1862, in ArgumentParser.parse_known_args(self, args, namespace)
   1861         err = _sys.exc_info()[1]
-> 1862         self.error(str(err))
   1863 else:

File /opt/conda/lib/python3.10/argparse.py:2583, in ArgumentParser.error(self, message)
   2582 args = {'prog': self.prog, 'message': message}
-> 2583 self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

File /opt/conda/lib/python3.10/argparse.py:2570, in ArgumentParser.exit(self, status, message)
   2569     self._print_message(message, _sys.stderr)
-> 2570 _sys.exit(status)

SystemExit: 2

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
    [... skipping hidden 1 frame]

File /opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2042, in InteractiveShell.showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2039 if exception_only:
   2040     stb = ['An exception has occurred, use %tb to see '
   2041            'the full traceback.\n']
-> 2042     stb.extend(self.InteractiveTB.get_exception_only(etype,
   2043                                                      value))
   2044 else:
   2045     try:
   2046         # Exception classes can customise their traceback - we
   2047         # use this in IPython.parallel for exceptions occurring
   2048         # in the engines. This should return a list of strings.

File /opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py:579, in ListTB.get_exception_only(self, etype, value)
    571 def get_exception_only(self, etype, value):
    572     """Only print the exception type and message, without a traceback.
    573 
    574     Parameters
   (...)
    577     value : exception value
    578     """
--> 579     return ListTB.structured_traceback(self, etype, value)

File /opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py:446, in ListTB.structured_traceback(self, etype, evalue, etb, tb_offset, context)
    443     chained_exc_ids.add(id(exception[1]))
    444     chained_exceptions_tb_offset = 0
    445     out_list = (
--> 446         self.structured_traceback(
    447             etype, evalue, (etb, chained_exc_ids),
    448             chained_exceptions_tb_offset, context)
    449         + chained_exception_message
    450         + out_list)
    452 return out_list

File /opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py:1112, in AutoFormattedTB.structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1110 else:
   1111     self.tb = tb
-> 1112 return FormattedTB.structured_traceback(
   1113     self, etype, value, tb, tb_offset, number_of_lines_of_context)

File /opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py:1006, in FormattedTB.structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1003 mode = self.mode
   1004 if mode in self.verbose_modes:
   1005     # Verbose modes need a full traceback
-> 1006     return VerboseTB.structured_traceback(
   1007         self, etype, value, tb, tb_offset, number_of_lines_of_context
   1008     )
   1009 elif mode == 'Minimal':
   1010     return ListTB.get_exception_only(self, etype, value)

File /opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py:859, in VerboseTB.structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
    850 def structured_traceback(
    851     self,
    852     etype: type,
   (...)
    856     number_of_lines_of_context: int = 5,
    857 ):
    858     """Return a nice text document describing the traceback."""
--> 859     formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
    860                                                            tb_offset)
    862     colors = self.Colors  # just a shorthand + quicker name lookup
    863     colorsnormal = colors.Normal  # used a lot

File /opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py:793, in VerboseTB.format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
    790 assert isinstance(tb_offset, int)
    791 head = self.prepare_header(etype, self.long_header)
    792 records = (
--> 793     self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
    794 )
    796 frames = []
    797 skipped = 0

File /opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py:848, in VerboseTB.get_records(self, etb, number_of_lines_of_context, tb_offset)
    842     formatter = None
    843 options = stack_data.Options(
    844     before=before,
    845     after=after,
    846     pygments_formatter=formatter,
    847 )
--> 848 return list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]

File /opt/conda/lib/python3.10/site-packages/stack_data/core.py:564, in FrameInfo.stack_data(cls, frame_or_tb, options, collapse_repeated_frames)
    548 @classmethod
    549 def stack_data(
    550         cls,
   (...)
    554         collapse_repeated_frames: bool = True
    555 ) -> Iterator[Union['FrameInfo', RepeatedFrames]]:
    556     """
    557     An iterator of FrameInfo and RepeatedFrames objects representing
    558     a full traceback or stack. Similar consecutive frames are collapsed into RepeatedFrames
   (...)
    562     and optionally an Options object to configure.
    563     """
--> 564     stack = list(iter_stack(frame_or_tb))
    566     # Reverse the stack from a frame so that it's in the same order
    567     # as the order from a traceback, which is the order of a printed
    568     # traceback when read top to bottom (most recent call last)
    569     if is_frame(frame_or_tb):

File /opt/conda/lib/python3.10/site-packages/stack_data/utils.py:97, in iter_stack(frame_or_tb)
     95 while frame_or_tb:
     96     yield frame_or_tb
---> 97     if is_frame(frame_or_tb):
     98         frame_or_tb = frame_or_tb.f_back
     99     else:

File /opt/conda/lib/python3.10/site-packages/stack_data/utils.py:90, in is_frame(frame_or_tb)
     89 def is_frame(frame_or_tb: Union[FrameType, TracebackType]) -> bool:
---> 90     assert_(isinstance(frame_or_tb, (types.FrameType, types.TracebackType)))
     91     return isinstance(frame_or_tb, (types.FrameType,))

File /opt/conda/lib/python3.10/site-packages/stack_data/utils.py:176, in assert_(condition, error)
    174 if isinstance(error, str):
    175     error = AssertionError(error)
--> 176 raise error

AssertionError: 
```

**Comment by lesteve** [comment]
This does not seem to be as bad as the original issue (which should be closed I think). In the latter case, the traceback is confusing but at least it does not crash IPython.

Not sure whether this is an issue in `IPython` or `stack_data`. FWIW on the failing `assert`:
```py
assert_(isinstance(frame_or_tb, (types.FrameType, types.TracebackType)))
```

`frame_or_tb` is a tuple where the first element is a traceback object:
```
ipdb> frame_or_tb
(<traceback object at 0x7f7264f00e40>, {140129298422176})
```

**Comment by karolinepauls** [comment]
This happens to me when using `%debug`.

while this snipped from an earlier post doesn't reproduce the issue for me:
```
In [13]: v = ValueError()

In [14]: v.__context__ = ValueError()

In [15]: raise v
```
calling `%debug` afterwards does.
