### ISSUE TITLE
verbose %autocall

### ISSUE THREAD

**Issue by sylvain-bougnoux** [ipython/ipython#12717]
Is there a way to suppress the verbosity of `%autocall`, especially for duplicate information, but possible for all (----->)
Like:
```
>a=0
>type a
------> type(a)
------> type(a)
------> type(a)
Out[20]: int
```

**Comment by MrMino** [comment]
@sylvain-bougnoux I cannot reproduce the duplication on 7.22, so I guess that has been fixed at some point. In order to quiet the output down, you'll need to run IPython with the following config flag:

```
ipython --TerminalInteractiveShell.show_rewritten_input=False
```

**Comment by sylvain-bougnoux** [comment]
OK thanks for the tip. It still happens on 7.16.1 (latest official release on pip **for python 3.6**), I guess I have to move to a new python version. Thanks again.
