### ISSUE TITLE
Incorrect traceback after `%autoreload` in IPython 9.x with `DeduperReloader` enabled

### ISSUE THREAD

**Issue by daeyun** [ipython/ipython#14900]
## Environment

item | version / value
-- | --
IPython | 9.0.0 – 9.3.0.dev0 (main)
Python | 3.12.3
executing | 2.2.0
stack_data | 0.6.3
OS | Ubuntu 24.04.1

(Problem does **not** occur on IPython 8.36 with the legacy reloader.)

## Minimal reproducible example

Run each cell in a fresh kernel exactly as shown, one after the other, waiting for each to finish before executing the next.

### Cell 1: setup and first failure (shows correct filename and context)

```python
import tempfile, os, sys, traceback
from IPython import get_ipython

# Named temporary directory
tmpdir = os.path.join(tempfile.gettempdir(), "autoreload_demo")
os.makedirs(tmpdir, exist_ok=True)
sys.path.insert(0, tmpdir)
mod_path = os.path.join(tmpdir, "mymod.py")

def write(src: str):
    with open(mod_path, "w") as f:
        f.write(src)

write("def buggy():\n    return 1/0\n")

ip = get_ipython()
ip.run_line_magic("load_ext", "autoreload")
ip.run_line_magic("autoreload", "2")

# --- Toggle these two lines and the problem disappears ----
# from IPython.extensions.deduperreload.deduperreload import DeduperReloader
# DeduperReloader.enabled = False
# -----------------------------------------------------------------------

import mymod

try:
    mymod.buggy()
except Exception:
    traceback.print_exc()
```

Traceback (correct):

```
File "/tmp/autoreload_demo/mymod.py", line 2, in buggy
    return 1/0
           ~^~
ZeroDivisionError: division by zero
```

### Cell 2: change the code (triggers autoreload)

```python
write("def buggy():\n    return 42/0\n")
```

### Cell 3: call the function again

```python
try:
    mymod.buggy()
except Exception:
    traceback.print_exc()
```

Traceback (**incorrect**: no filename and context):

```
File "<string>", line 2, in buggy
ZeroDivisionError: division by zero
```

Expected:

```
File "/tmp/autoreload_demo/mymod.py", line 2, in buggy
    return 42/0
           ~~^~
ZeroDivisionError: division by zero
```

### Observations
- Running the three snippets in a single cell, or queuing all three cells at once (e.g., Run All), does not reproduce the problem. Any reload executed from subsequent cells produces the incorrect traceback.
- Uncommenting the two "toggle" lines (disabling `DeduperReloader` after `%autoreload` is initialized) restores correct behavior.

### Motivation

When tracebacks lose the filename and code context, so you can't see which line in the edited file raised the error, it makes iterative development much harder.

**Comment by krassowski** [comment]
Closing as fixed in IPython 9.5.0.

**Comment by Gigahawk** [comment]
I think I am still seeing the same/similar issue in IPython 9.11.0 although with pdb instead of a traceback, captured in this pytest test:

https://github.com/Gigahawk/ipython-b3d/blob/7809bf70808ef3d246a5dd5a2506c1b75415f68d/tests/test_import.py#L52-L129

Note that `ipb3d` is pretty much just a wrapper to IPython, only thing of note here is the addition of a `%r` magic which just `%run`s a file.
