### ISSUE TITLE
Bad result of ipython nbconvert --to rst

### ISSUE THREAD

**Issue by paugier** [ipython/ipython#7907]
The conversion to rst leads to bad rst files since

1. there is no blank line just after a code block
2. many spaces are inserted before the code of a Raw NBConvert cell.

As a bad workaround I modified the template files to get the correct behavior (I do not know Jinja!):

- issue 1:

        diff IPython/nbconvert/templates/rst.tpl IPython/nbconvert/templates/rst.tpl_orig
        14,15c14
        < {{ cell.input | indent }}
        < {{ '' }}
        ---
        > {{ cell.input | indent}}
  
- issue 2:

        diff IPython/nbconvert/templates/skeleton/null.tpl IPython/nbconvert/templates/skeleton/null.tpl_orig
        81c81
        < {{ cell.source }}
        ---
        >                 {{ cell.source }}

**Comment by mwaskom** [comment]
Is this in 3.0? This looks like #6262, which has been fixed in the new version.

**Comment by paugier** [comment]
It was not on 3.0 (it was in 2.4) but after the upgrade to 3.0, there are still the same kind of problems. In 3.0, there is no blank line after the code blocks and there is no blank lines before and after the Raw NBConvert blocks!

**Comment by mwaskom** [comment]
I've noticed that too. Using 3.0, if I take a notebook that looks like this:

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Testing rst conversion"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "Here is some raw text.\n",
    "\n",
    "We'd like to write some sphinx docs in this cell, and then show some python code in the next cell."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[0, 1, 4, 9, 16]\n"
     ]
    }
   ],
   "source": [
    "x = range(5)\n",
    "print([x_i ** 2 for x_i in x])"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "Now we can say something about what we did."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```

and run `ipython nbconvert --to rst test_notebook.ipynb`

it yields

```

Testing rst conversion
======================
Here is some raw text.

We'd like to write some sphinx docs in this cell, and then show some python code in the next cell.
.. code:: python

    x = range(5)
    print([x_i ** 2 for x_i in x])

.. parsed-literal::

    [0, 1, 4, 9, 16]

Now we can say something about what we did.
```

Which breaks the rst markup.

**Comment by Carreau** [comment]
Does #7917 fix that for you ?

**Comment by paugier** [comment]
Yes [#7917](https://github.com/ipython/ipython/pull/7917) fixes it. Thank you for this fast fix and in general for IPython - Jupiter!

**Comment by Carreau** [comment]
> Yes #7917 fixes it

Great ! 

> Thank you for this fast fix and in general for IPython - Jupiter!

Thanks !
