### ISSUE TITLE
IPython notebook crashes when trying to use multiprocessing after plotting an image

### ISSUE THREAD

**Issue by astrofrog** [ipython/ipython#8414]
On MacOS X, using Python 3.4 from MacPorts, the following notebook:

http://nbviewer.ipython.org/gist/astrofrog/89e4c4b4889e8e412f56

causes the IPython kernel to crash with the following error:

https://gist.githubusercontent.com/astrofrog/89e4c4b4889e8e412f56/raw/1ceaa71bca14e38851e77a9b494cbc2dde2a0ab5/ipython_error.log

and MacOS X also produces a crash report:

https://gist.githubusercontent.com/astrofrog/89e4c4b4889e8e412f56/raw/c4e1865135ddbfed94cc913036ac71d7e6a3568b/osx.log

The above errors are for IPython 2.0. In IPython 3.0, I also get the kernel crashing and MacOS X giving me a report, but the IPython terminal log is shorter:

```
Assertion failed: ok (mailbox.cpp:84)
Assertion failed: ok (mailbox.cpp:84)
```

If I use conda on the other hand, no error occurs. With the MacPorts install, if I don't plot the image, no error occurs.

¯\\_(ツ)_/¯

**Comment by cdeil** [comment]
I see the same error (with Ipython 3 and Macports):
```
[I 18:46:19.149 NotebookApp] Kernel started: 11e145e9-1137-4541-ac3b-f245a6d72598
Assertion failed: ok (mailbox.cpp:84)
[I 18:46:28.150 NotebookApp] KernelRestarter: restarting kernel (1/5)
```

**Comment by minrk** [comment]
What version of pyzmq and libzmq?

**Comment by astrofrog** [comment]
For me, pyzmq 14.6.0 and zmq 3.2.5

**Comment by takluyver** [comment]
@minrk is this something that has been fixed?

**Comment by astrofrog** [comment]
@takluyver @minrk - this issue still occurs with IPython 4.0.3 and Jupyter 4.0.6.

**Comment by minrk** [comment]
Difficult to say, I still haven't been able to reproduce it. I can try some more, though. Often, asserts are libzmq bugs which may be fixed in more recent zmq versions. The other potential cause, given that multiprocessing is involved, is that it's a failure in the fork-safety protections, which would be on IPython's (jupyter_client and/or ipykernel, specifically) side.

@astrofrog are you still on libzmq-3.2.5 and pyzmq-14.6?

**Comment by astrofrog** [comment]
@minrk - it looks like I'm using pyzmq 14.3.1 and zmq 3.2.4 (I reinstalled MacPorts, not sure why the versions are *older* than before)

**Comment by astrofrog** [comment]
Ah, I just forced an upgrade of pyzmq to 15.2.0 and the issue is gone.

**Comment by takluyver** [comment]
Hurray! :sparkles:
