### ISSUE TITLE
Cannot complete namespace packages (was Where did %rehash go?)

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#8875]
Either %rehash was mistakenly removed, or the doc of %rehashx 

```
In [9]: %rehashx?
Docstring:
Update the alias table with all executable files in $PATH.

This version explicitly checks that every entry in $PATH is a file
with execute access (os.X_OK), so it is much slower than %rehash.

Under Windows, it checks executability as a match against a
'|'-separated string of extensions, stored in the IPython config
variable win_exec_ext.  This defaults to 'exe|com|bat'.

This function also resets the root module cache of module completer,
used on slow filesystems.
File:      /usr/lib/python3.5/site-packages/IPython/core/magics/osm.py

In [10]: %rehash?
Object `%rehash` not found.
```

As a side note I noticed this when I realized that `import mpl_` would not complete `mpl_toolkits` and tried to `%rehash` my cache; I still don't know how to get this to complete properly.

**Comment by minrk** [comment]
Wow, that's an out-of-date docstring. The last version with `%rehash` was 0.10 about five years ago. `%rehashx` is all that we have now. Does it not clear your module completer cache?

**Comment by anntzer** [comment]
At least I still can't complete `import mpl_` into `import mpl_toolkits`.

**Comment by minrk** [comment]
Hm. What's your Python, IPython and OS version? And what do you get for `get_ipython().db.get('rootmodules_cache')`? It only caches imports when it takes a long time to compute them, otherwise it computes them on the fly.

**Comment by jenshnielsen** [comment]
Could it be related to `mpl_toolkits` being a namespace package? Something that we (mpl developers that is)  should perhaps change in the future due to other issues.

**Comment by minrk** [comment]
@jenshnielsen yes, it's possible, however I do find `mpl_toolkits` in my import completions, so I'm trying to figure out what is different between the two environments.

**Comment by anntzer** [comment]
Arch Linux standard packages, on a clean (new) profile.
```
Python 3.5.0 (default, Sep 20 2015, 11:28:25) 
IPython 4.0.0 -- An enhanced Interactive Python.
```
`get_ipython().db.get('rootmodules_cache')` returns None.

**Comment by jenshnielsen** [comment]
@minrk I can reproduce the issue on OSX 10.11 with my pip installed dev ca .1.5.rc2 version of matplotlib but not in a Conda env on the same machine. Not sure what the difference is

**Comment by minrk** [comment]
@jenshnielsen thanks for narrowing it down. It may have something to do with namespace packages.

**Comment by Carreau** [comment]
Rename to reflect remaining issue about completion of namespace packages.
And bump to 5.0

**Comment by takluyver** [comment]
If on Python 3 it's a PEP 420 namespace package, I don't think there's any simple way to identify it as a package for tab completion. The normal indicator of a package is that it contains an `__init__.py` file, and PEP 420 namespace packages don't have that. I don't think we should assume any directory could be a namespace package.

**Comment by Carreau** [comment]
Bumping to 6.0 as there are few change we can actually so've it for 5.0 if we don't know the reason.

**Comment by Carreau** [comment]
Fixed by #10182 (Reintegrate Jedi), Jedi is able to find this and tell it's a module. 

<img width="303" alt="screen shot 2017-02-09 at 13 04 47" src="https://cloud.githubusercontent.com/assets/335567/22803089/6102bb32-eec8-11e6-8b5d-ac273d590633.png">

`--jedi/ipython--` is just a visual delimiter between the 2 sources of completions. 

Closing, feel free to reopen if it's still failing on master for you.

**Comment by anntzer** [comment]
This is still failing for me as of 6.1.0 and as of master (just pulled).  Could the issue be reopened?  Thanks.

**Comment by takluyver** [comment]
Jupytercon starts tomorrow, so it may be a while before @Carreau can investigate.
